Structure du repo
VilledeMontreal/MontrealEnCommun pull request #2
Opened 2021-11-07 15:39 UTC by houssamkhalifeh

Dans le but de faciliter la collaboration et la découvrabilité des contributions j'ai créé des sous répertoires. Cela nous donnera la possibilité de mieux catégoriser nos échanges comme une alternative à la création de repos à part entier.

2021-11-07 16:31 UTC, houssamkhalifeh commented
Le DCO n'est pas vraiement requis pour MeC. Je vote pour l'enlever.

2021-11-29 14:00 UTC, housssec requested changes
Peut-être ajouter des sous-répertoire pour les projets des partenaires.

2021-11-29 14:35 UTC, housssec approved these changes

2021-11-29 14:42 UTC, pagbokou-artm commented on ProjetsPartenaires/Gabarit/Projet-1.md
> +Modules: faire référence au référentiel des module au besoin
svp, revoir "des modules"

2021-11-29 14:43 UTC, pagbokou-artm approved these changes
Revu et accepté.

2021-12-05 19:28 UTC, cliambrown approved these changes
Looks good!

2022-01-26 21:01 UTC, Jduhommet commented
Ça me semble ok aussi ! Merci Houssam.

2022-01-31 12:59 UTC, merged

2022-01-31 13:51 UTC, houssamkhalifeh commented
> Ça me semble ok aussi ! Merci Houssam.

Merci Joanne! STP accepter l'invitation pour que je puisse t'ajouter comme contributeur externe. @Jduhommet